"""Add indexes, timestamps, and cost attribution

Revision ID: cfbd2edeb4e2
Revises: 8593bec6cac7
Create Date: 2026-08-18 13:47:21.447651

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cfbd2edeb4e2'
down_revision: Union[str, Sequence[str], None] = '8593bec6cac7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ai_cost_logs', sa.Column('image_id', sa.UUID(), nullable=True))
    op.add_column('ai_cost_logs', sa.Column('post_id', sa.UUID(), nullable=True))
    op.alter_column('ai_cost_logs', 'job_type',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('ai_cost_logs', 'model',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('ai_cost_logs', 'tokens_used',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('ai_cost_logs', 'estimated_cost',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('ai_cost_logs', 'timestamp',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.create_foreign_key(None, 'ai_cost_logs', 'images', ['image_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'ai_cost_logs', 'posts', ['post_id'], ['id'], ondelete='CASCADE')
    op.add_column('image_metadata', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.alter_column('image_metadata', 'image_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('image_metadata', 'subject',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('image_metadata', 'category',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('image_metadata', 'attributes',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('image_metadata', 'caption',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('image_metadata', 'confidence',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.create_index(op.f('ix_image_metadata_category'), 'image_metadata', ['category'], unique=False)
    op.create_index(op.f('ix_image_metadata_subject'), 'image_metadata', ['subject'], unique=False)
    op.create_unique_constraint(None, 'image_metadata', ['image_id'])
    op.drop_constraint(op.f('image_metadata_image_id_fkey'), 'image_metadata', type_='foreignkey')
    op.create_foreign_key(None, 'image_metadata', 'images', ['image_id'], ['id'], ondelete='CASCADE')
    op.add_column('images', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('images', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.alter_column('images', 'filename',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('images', 'status',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.add_column('matches', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('matches', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.alter_column('matches', 'post_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('matches', 'image_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('matches', 'similarity_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('matches', 'status',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_index(op.f('ix_matches_image_id'), 'matches', ['image_id'], unique=False)
    op.create_index(op.f('ix_matches_post_id'), 'matches', ['post_id'], unique=False)
    op.create_unique_constraint('uq_post_image_match', 'matches', ['post_id', 'image_id'])
    op.drop_constraint(op.f('matches_image_id_fkey'), 'matches', type_='foreignkey')
    op.drop_constraint(op.f('matches_post_id_fkey'), 'matches', type_='foreignkey')
    op.create_foreign_key(None, 'matches', 'images', ['image_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'matches', 'posts', ['post_id'], ['id'], ondelete='CASCADE')
    op.add_column('posts', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('posts', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.alter_column('posts', 'title',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('posts', 'content',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('posts', 'content',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('posts', 'title',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('posts', 'updated_at')
    op.drop_column('posts', 'created_at')
    op.drop_constraint(None, 'matches', type_='foreignkey')
    op.drop_constraint(None, 'matches', type_='foreignkey')
    op.create_foreign_key(op.f('matches_post_id_fkey'), 'matches', 'posts', ['post_id'], ['id'])
    op.create_foreign_key(op.f('matches_image_id_fkey'), 'matches', 'images', ['image_id'], ['id'])
    op.drop_constraint('uq_post_image_match', 'matches', type_='unique')
    op.drop_index(op.f('ix_matches_post_id'), table_name='matches')
    op.drop_index(op.f('ix_matches_image_id'), table_name='matches')
    op.alter_column('matches', 'status',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('matches', 'similarity_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('matches', 'image_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('matches', 'post_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_column('matches', 'updated_at')
    op.drop_column('matches', 'created_at')
    op.alter_column('images', 'status',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('images', 'filename',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('images', 'updated_at')
    op.drop_column('images', 'created_at')
    op.drop_constraint(None, 'image_metadata', type_='foreignkey')
    op.create_foreign_key(op.f('image_metadata_image_id_fkey'), 'image_metadata', 'images', ['image_id'], ['id'])
    op.drop_constraint(None, 'image_metadata', type_='unique')
    op.drop_index(op.f('ix_image_metadata_subject'), table_name='image_metadata')
    op.drop_index(op.f('ix_image_metadata_category'), table_name='image_metadata')
    op.alter_column('image_metadata', 'confidence',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('image_metadata', 'caption',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('image_metadata', 'attributes',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('image_metadata', 'category',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('image_metadata', 'subject',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('image_metadata', 'image_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_column('image_metadata', 'created_at')
    op.drop_constraint(None, 'ai_cost_logs', type_='foreignkey')
    op.drop_constraint(None, 'ai_cost_logs', type_='foreignkey')
    op.alter_column('ai_cost_logs', 'timestamp',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('ai_cost_logs', 'estimated_cost',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('ai_cost_logs', 'tokens_used',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('ai_cost_logs', 'model',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('ai_cost_logs', 'job_type',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('ai_cost_logs', 'post_id')
    op.drop_column('ai_cost_logs', 'image_id')
    # ### end Alembic commands ###
